export const products = [
  {
    id: 1,
    idpro: 0,
    category: 'Electronics',
    name: 'Digital Camera,2.4 inch 24megapixels vlogging Camera,Mini Digital Camera,Screen Camera with Digital Zoom Macro Compact Cameras for Beginners',
    price: 39.99,
    description: 'The digital camera supports 24MP resolution JPEG format images and 1080p resolution MOV format videos.The built-in flash lamp ensures that you can take clear pictures even in dark environment.The digital camera has a 2.4-inch TFT high-definition screen. You can view your photos on the screen.The digital camera supports up to 32GB micro SD card (micro SD card is included in the package, you dont need to purchase it separately)',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/716nbybT64L._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Digital-24megapixels-vlogging-Compact-Beginners/dp/B08NG84WND/ref=sr_1_1_sspa?dchild=1&qid=1615014824&rnid=502394&s=electronics&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyN09HN01WTEVWMVhRJmVuY3J5cHRlZElkPUEwNDY0MTA5M1RLSlI3T0QzVlVMQiZlbmNyeXB0ZWRBZElkPUEwMjU0MTU3MU9ZV0xBMlAzTkxUNCZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl'
  },
  {
    id: 1,
    idpro: 1,
    category: 'Electronics',
    name: 'Sony a7 III (ILCE7M3K/BQ) Full-frame Mirrorless Interchangeable-Lens Camera with 28-70mm Lens with 3-Inch LCD, Black',
    price: 1898.00,
    description: 'Advanced 24.2MP BSI Full-frame Image Sensor w/ 1.8X readout speed Advanced 24.2MP Back-Illuminated 35mm Full-frame Image Sensor',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/91rQ3XfEYzL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Sony-Full-frame-Mirrorless-Interchangeable-Lens-ILCE7M3K/dp/B07B45D8WV/ref=sr_1_7?dchild=1&qid=1615014824&rnid=502394&s=electronics&sr=1-7'
  },
  {
    id: 1,
    idpro: 2,
    name: 'Led Video Lighting Kit Dimmable 5600K USB 70 LED Video Light with Mini Adjustable Tripod Stand and Color Filters for Table Top/Low Angle Photo Video Studio Shooting (3 Pack)',
    category: 'Electronics',
    price: 49.99,
    description: '【MULTIPLE-USE LED LIGHTING SET】 The small LED panel light (5.73×3.78 inches/14.5× 9.6 centimeters) can be 180 degree adjustable, meeting your different demands on suitable shooting angle; Designed with convenient USB plug, you can plug it in your desktop PC, mobile power, charging plug or your USB socket at any time you want',
    rating: '4.5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/611zzDaRgaL._AC_SL1154_.jpg',
    link: 'https://www.amazon.com/Lighting-Dimmable-Adjustable-Filters-Shooting/dp/B08DNMGNRK/ref=sr_1_1_sspa?dchild=1&qid=1615015310&rnid=502394&s=electronics&sr=1-1-spons&psc=1&smid=A3AO9QDNU8GKEI&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyS0VWS0JQSlFWQU02JmVuY3J5cHRlZElkPUEwOTQ0NzMwQ01LVDNBTDlONTZLJmVuY3J5cHRlZEFkSWQ9QTA5OTI2NzYyVkNJWUNBMzUxWDk3JndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='
  },
  {
    id: 1,
    idpro: 3,
    name: 'Video Conference Lighting,6.3" Selfie Ring Light',
    category: 'Electronics',
    price: 23.99,
    description: '6.3 inch compact design with an anti-scratch mounting clamp (Max Mouth Opening Size:3.5 cm) allows this ring light to be mounted on your desk, laptop, chair, bed, conference table, even your PC monitor, laptop and anywhere you desire with strong stability. The weighted metal clamp will keep your LED ring light in balance even just place simply on the table for using.',
    rating: '4.7/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71yfX8mHvWL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Conference-Lighting-Conferencing-Dimmable-Monitor/dp/B08K2TMGBF/ref=sr_1_2?dchild=1&qid=1615015408&rnid=502394&s=electronics&sr=1-2'
  },
  {
    id: 1,
    idpro: 4,
    name: 'IVISII 19 inch Ring Light with Remote Controller and Stand ipad Holder,60W Bi-Color with 4 Color Soft Filters for Live Stream/Makeup/YouTube Video/TikTok/Zoom/Photography',
    category: 'Electronics',
    price: 159.99,
    description: '1x 19"Ring Light, 1x 74.8 inches/188cm Light Stand, 1x Carrying Bag, 1x Wireless Remoter, 1x Bluetooth Remoter, 4x Plastic Diffusion filter( White/Blue/Red/Green ), 1x iPad Holder,1x Phone Holder, 3x Camera mounting bracket, 1x US Plug, 1x Europe Plug',
    rating: '4.5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/715fh2tGM4L._AC_SL1194_.jpg',
    link: 'https://www.amazon.com/Controller-Bi-Color-3000K-5800K-TLCI-%E2%89%A599-Facebook/dp/B07SW5G7XB/ref=sr_1_15?dchild=1&qid=1615015408&rnid=502394&s=electronics&sr=1-15'
  },

  {
    id: 2,
    idpro: 5,
    name: 'HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA)',
    category: 'Computers',
    price: 2.99,
    description: 'OUTSTANDING VISUALS – This FHD display with IPS technology gives you brilliant visuals and unforgettable quality; with a maximum resolution of 1920 x 1080 at 75 Hz, you’ll experience the image accuracy and wide-viewing spectrums of premium tablets and mobile devices',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/HP-24mh-FHD-Monitor-Built/dp/B08BF4CZSV/ref=sr_1_1?dchild=1&qid=1615016526&s=computers-intl-ship&sr=1-1'
  },
  {
    id: 2,
    idpro: 6,
    name: 'ASUS ROG Strix Helios GX601 White Edition RGB Mid-Tower Computer Case for ATX/EATX Motherboards with tempered glass, aluminum frame, GPU braces, 420mm radiator support and Aura Sync',
    category: 'Computers',
    price: 319.99,
    description: 'Premium design & aesthetics: Made for showcase builds with three tempered-glass panels, brushed-aluminum frame and integrated Aura Sync RGB front lighting',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/81utiMzGFdL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/ASUS-GX601-Mid-Tower-Computer-Motherboards/dp/B0896Y1K7B/ref=sr_1_5?dchild=1&keywords=computer&qid=1615016340&s=pc&sr=1-5'
  },
  {
    id: 2,
    idpro: 7,
    name: 'HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA)',
    category: 'Computers',
    price: 2.99,
    description: 'OUTSTANDING VISUALS – This FHD display with IPS technology gives you brilliant visuals and unforgettable quality; with a maximum resolution of 1920 x 1080 at 75 Hz, you’ll experience the image accuracy and wide-viewing spectrums of premium tablets and mobile devices',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/HP-24mh-FHD-Monitor-Built/dp/B08BF4CZSV/ref=sr_1_1?dchild=1&qid=1615016526&s=computers-intl-ship&sr=1-1'
  },
  {
    id: 2,
    idpro: 8,
    name: 'HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA)',
    category: 'Computers',
    price: 2.99,
    description: 'OUTSTANDING VISUALS – This FHD display with IPS technology gives you brilliant visuals and unforgettable quality; with a maximum resolution of 1920 x 1080 at 75 Hz, you’ll experience the image accuracy and wide-viewing spectrums of premium tablets and mobile devices',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/HP-24mh-FHD-Monitor-Built/dp/B08BF4CZSV/ref=sr_1_1?dchild=1&qid=1615016526&s=computers-intl-ship&sr=1-1'
  },
  {
    id: 2,
    idpro: 9,
    name: 'HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA)',
    category: 'Computers',
    price: 2.99,
    description: 'OUTSTANDING VISUALS – This FHD display with IPS technology gives you brilliant visuals and unforgettable quality; with a maximum resolution of 1920 x 1080 at 75 Hz, you’ll experience the image accuracy and wide-viewing spectrums of premium tablets and mobile devices',
    rating: '5/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/HP-24mh-FHD-Monitor-Built/dp/B08BF4CZSV/ref=sr_1_1?dchild=1&qid=1615016526&s=computers-intl-ship&sr=1-1'
  },
  {
    id: 3,
    idpro: 10,
    name: 'Smart WiFi Light Bulb, LED RGBCW Color Changing, Compatible with Alexa and Google Home Assistant, No Hub Required, A19 E26 Multicolor LUMIMAN 2 Pack',
    category: 'Smart Home',
    price: 14.99,
    description: 'VOICE CONTROL - LUMIMAN Smart bulb no hub compatible with Alexa Echo (via PlusMinus skill), Echo dot and Google Home Assistant, control the wifi bulb via your voice, No hub required. (e.g. ‘Alexa, set the bedroom to purple’)',
    rating: '4.6/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/61axAPdYt3L._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Changing-Compatible-Assistant-Multicolor-LUMIMAN/dp/B07DLSNNDS/ref=lp_21217035011_1_1?s=specialty-aps'
  },
  {
    id: 3,
    idpro: 11,
    name: 'Facebook Portal Plus - Smart Video Calling 15.6” Touch Screen Display with Alexa - Black',
    category: 'Smart Home',
    price: 15.59,
    description: 'Easily video call with friends and family using your Messenger or WhatsApp account, even if they dont have Portal.',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71a4UKUknlL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/dp/B07HFWG8S4/ref=s9_acsd_al_bw_c2_x_0_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=T2G1QYDVEGHXRBBT2Z0E&pf_rd_t=101&pf_rd_p=f8153587-9f7d-46c3-86af-b88f5e0c93ac&pf_rd_i=21216812011'
  },
  {
    id: 3,
    idpro: 12,
    name: 'Facebook Portal Plus - Smart Video Calling 15.6” Touch Screen Display with Alexa - Black',
    category: 'Smart Home',
    price: 15.59,
    description: 'Easily video call with friends and family using your Messenger or WhatsApp account, even if they dont have Portal.',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71a4UKUknlL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/dp/B07HFWG8S4/ref=s9_acsd_al_bw_c2_x_0_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=T2G1QYDVEGHXRBBT2Z0E&pf_rd_t=101&pf_rd_p=f8153587-9f7d-46c3-86af-b88f5e0c93ac&pf_rd_i=21216812011'
  },
  {
    id: 3,
    idpro: 13,
    name: 'Facebook Portal Plus - Smart Video Calling 15.6” Touch Screen Display with Alexa - Black',
    category: 'Smart Home',
    price: 15.59,
    description: 'Easily video call with friends and family using your Messenger or WhatsApp account, even if they dont have Portal.',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71a4UKUknlL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/dp/B07HFWG8S4/ref=s9_acsd_al_bw_c2_x_0_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=T2G1QYDVEGHXRBBT2Z0E&pf_rd_t=101&pf_rd_p=f8153587-9f7d-46c3-86af-b88f5e0c93ac&pf_rd_i=21216812011'
  },
  {
    id: 3,
    idpro: 14,
    name: 'Facebook Portal Plus - Smart Video Calling 15.6” Touch Screen Display with Alexa - Black',
    category: 'Smart Home',
    price: 15.59,
    description: 'Easily video call with friends and family using your Messenger or WhatsApp account, even if they dont have Portal.',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71a4UKUknlL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/dp/B07HFWG8S4/ref=s9_acsd_al_bw_c2_x_0_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=T2G1QYDVEGHXRBBT2Z0E&pf_rd_t=101&pf_rd_p=f8153587-9f7d-46c3-86af-b88f5e0c93ac&pf_rd_i=21216812011'
  },
  {
    id: 4,
    idpro: 15,
    name: 'Deluxe Art Set,81 Pcs Art Supplies Painting&Drawing Kit,Oil Pastels,Watercolor Cakes,Color Pencils,Art Markers,Erasers,Paintbrushes,Pencil Sharpener, Gift for Kids Teens Girls Boys Children',
    category: 'Arts',
    price: 24.99,
    description: 'We put childrens health and safety first.All crayons,pigments and pastels in this art box are non-toxic,tested and obtained AP (approved product) and HL (health label (non-toxic) certification) from ACMI (Art and Creative Materials Institute,Inc.),It also complies with ASTM D4236 (standard specification for labeling art materials for chronic health hazards).',
    rating: '4/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/71uXoT7Yl7L._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Supplies-Painting-Watercolor-Paintbrushes-Sharpener/dp/B08QJH7534/ref=sr_1_1_sspa?dchild=1&qid=1615017123&s=arts-crafts-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFCRDY2UE5FTUtUWFkmZW5jcnlwdGVkSWQ9QTAwMjY3OTZTNUc5TjJKSEhQSlQmZW5jcnlwdGVkQWRJZD1BMDc4NjY5MTFLUFVKSlNKNFIwS0kmd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
  },
  {
    id: 4,
    idpro: 16,
    name: 'Castle Art Supplies 72 Premium Colored Coloring Pencils Set for Adults Artists Beginners | Ideal for Drawing Sketching Shading | Artist Soft Series Lead Cores with Vibrant Colors',
    category: 'Arts',
    price: 39.99,
    description: '“AN ABSOLUTE JOY TO USE” this selection of 72 premium colored pencils have fast become the ‘pencil set of choice’ for thousands of aspiring artists and colorists who dream of creating beautiful artwork in this popular medium. The rich, velvety leads are highly pigmented, and lay down lots of vivid color with minimal effort, making these easy-to-use pencils an absolute must!',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/81Bqnx6ObtL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Castle-Art-Supplies-Colored-Coloring/dp/B06ZZNF7GS/ref=sr_1_17_sspa?dchild=1&qid=1615017305&s=arts-crafts-intl-ship&sr=1-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNDBSNzNLRjVIUjkmZW5jcnlwdGVkSWQ9QTAzMjEzODFPWFdCSEhPSUpLSlEmZW5jcnlwdGVkQWRJZD1BMDgzMzUwMTE2OVFCSlUwWVRMVVkmd2lkZ2V0TmFtZT1zcF9tdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
  },
  {
    id: 4,
    idpro: 17,
    name: 'Castle Art Supplies 72 Premium Colored Coloring Pencils Set for Adults Artists Beginners | Ideal for Drawing Sketching Shading | Artist Soft Series Lead Cores with Vibrant Colors',
    category: 'Arts',
    price: 39.99,
    description: '“AN ABSOLUTE JOY TO USE” this selection of 72 premium colored pencils have fast become the ‘pencil set of choice’ for thousands of aspiring artists and colorists who dream of creating beautiful artwork in this popular medium. The rich, velvety leads are highly pigmented, and lay down lots of vivid color with minimal effort, making these easy-to-use pencils an absolute must!',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/81Bqnx6ObtL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Castle-Art-Supplies-Colored-Coloring/dp/B06ZZNF7GS/ref=sr_1_17_sspa?dchild=1&qid=1615017305&s=arts-crafts-intl-ship&sr=1-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNDBSNzNLRjVIUjkmZW5jcnlwdGVkSWQ9QTAzMjEzODFPWFdCSEhPSUpLSlEmZW5jcnlwdGVkQWRJZD1BMDgzMzUwMTE2OVFCSlUwWVRMVVkmd2lkZ2V0TmFtZT1zcF9tdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
  },
  {
    id: 4,
    idpro: 18,
    name: 'Castle Art Supplies 72 Premium Colored Coloring Pencils Set for Adults Artists Beginners | Ideal for Drawing Sketching Shading | Artist Soft Series Lead Cores with Vibrant Colors',
    category: 'Arts',
    price: 39.99,
    description: '“AN ABSOLUTE JOY TO USE” this selection of 72 premium colored pencils have fast become the ‘pencil set of choice’ for thousands of aspiring artists and colorists who dream of creating beautiful artwork in this popular medium. The rich, velvety leads are highly pigmented, and lay down lots of vivid color with minimal effort, making these easy-to-use pencils an absolute must!',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/81Bqnx6ObtL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Castle-Art-Supplies-Colored-Coloring/dp/B06ZZNF7GS/ref=sr_1_17_sspa?dchild=1&qid=1615017305&s=arts-crafts-intl-ship&sr=1-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNDBSNzNLRjVIUjkmZW5jcnlwdGVkSWQ9QTAzMjEzODFPWFdCSEhPSUpLSlEmZW5jcnlwdGVkQWRJZD1BMDgzMzUwMTE2OVFCSlUwWVRMVVkmd2lkZ2V0TmFtZT1zcF9tdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
  },
  {
    id: 4,
    idpro: 19,
    name: 'Castle Art Supplies 72 Premium Colored Coloring Pencils Set for Adults Artists Beginners | Ideal for Drawing Sketching Shading | Artist Soft Series Lead Cores with Vibrant Colors',
    category: 'Arts',
    price: 39.99,
    description: '“AN ABSOLUTE JOY TO USE” this selection of 72 premium colored pencils have fast become the ‘pencil set of choice’ for thousands of aspiring artists and colorists who dream of creating beautiful artwork in this popular medium. The rich, velvety leads are highly pigmented, and lay down lots of vivid color with minimal effort, making these easy-to-use pencils an absolute must!',
    rating: '4.8/5',
    likes: 0,
    source: 'https://images-na.ssl-images-amazon.com/images/I/81Bqnx6ObtL._AC_SL1500_.jpg',
    link: 'https://www.amazon.com/Castle-Art-Supplies-Colored-Coloring/dp/B06ZZNF7GS/ref=sr_1_17_sspa?dchild=1&qid=1615017305&s=arts-crafts-intl-ship&sr=1-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNDBSNzNLRjVIUjkmZW5jcnlwdGVkSWQ9QTAzMjEzODFPWFdCSEhPSUpLSlEmZW5jcnlwdGVkQWRJZD1BMDgzMzUwMTE2OVFCSlUwWVRMVVkmd2lkZ2V0TmFtZT1zcF9tdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
  }
];
