# Generated by Django 3.1.7 on 2021-04-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'verbose_name_plural': 'Demo'},
        ),
    ]
