# Generated by Django 3.1.7 on 2021-04-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210417_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vacancies', to='api.company'),
        ),
    ]
